name: matrix_multiplyer_android
description: "A new Flutter plugin project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: '>=3.2.6 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  matrix_multiplyer_platform_interface:
    path: ../matrix_multiplyer_platform_interface

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.matrix_multiplyer_android
        pluginClass: MatrixMultiplyerAndroidPlugin
        dartPluginClass: MatrixMultiplyerAndroid